const numero1 = 20;
const numero3 = 30;

console.log(numero1);

try {
    console.log (numero2)
} catch (error) {
    console.log(error);
}

console.log(numero3)


//se usa try catch solo en situaciones muy especificas
//para que no deje de funcionar el codigo en caso de un error
//por ejemplo si un pago se pudo completar o no